<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ5kfwqy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ5kfwqy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ5kfwqy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ5kfwqy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ5kfwqy\App_KernelDevDebugContainer([
    'container.build_hash' => 'J5kfwqy',
    'container.build_id' => '7ec80a74',
    'container.build_time' => 1732028819,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ5kfwqy');
